name = "handelwebsite"

account_id = "835e77b528d856d2d4eb62c7ebf1d406"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
compatibility_date = "2024-03-16" # Update to the latest
[build]
command = "pnpm run build"
[assets]
binding = "ASSETS"
directory = "./.svelte-kit/cloudflare/"
[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
[observability.logs]
invocation_logs = true