name = "handelwebsite"

account_id = "835e77b528d856d2d4eb62c7ebf1d406"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
compatibility_date = "2024-03-16" # Update to the latest
[build]
command = "pnpm run build"
upload_format = "modules"
dir = ".svelte-kit/cloudflare"
[assets]
directory = "./static"
binding = "ASSETS"