name = "handelwebsite"

account_id = "835e77b528d856d2d4eb62c7ebf1d406"
type = "javascript"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
compatibility_date = "2024-03-16" # Update to the latest