name: Format Check

on: [push, pull_request]

env:
  PUBLIC_SUPABASE_URL: 'https://yrwuyfnwhwtrhzemitex.supabase.co'
  PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyd3V5Zm53aHd0cmh6ZW1pdGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNTUxMDUsImV4cCI6MjA1NzYzMTEwNX0.bVvsWx_xTWX3nel15JOa6jlQ-jholuH2bzAviiBskiQ"
  PRIVATE_SUPABASE_SERVICE_ROLE: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
  PRIVATE_STRIPE_API_KEY: "fake_strip_api_key"

jobs:
  build_and_test:
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: NPM install
        run: npm install

      - name: Check Code Format
        run: npm run format_check

      - name: Download go misspell utility
        run: go install github.com/client9/misspell/cmd/misspell@latest

      - name: Run misspell to fine misspelled words
        run: misspell -error ./src README.md
