name: Linting

on: [push, pull_request]

env:
  VITE_PUBLIC_SUPABASE_URL: 'https://yrwuyfnwhwtrhzemitex.supabase.co'
  VITE_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyd3V5Zm53aHd0cmh6ZW1pdGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNTUxMDUsImV4cCI6MjA1NzYzMTEwNX0.bVvsWx_xTWX3nel15JOa6jlQ-jholuH2bzAviiBskiQ'
  PRIVATE_SUPABASE_SERVICE_ROLE: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
  PRIVATE_STRIPE_API_KEY: "fake_strip_api_key"

jobs:
  build_and_test:
    name: Linting and Typechecking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: NPM install
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Typechecking
        run: npm run check
